/*
 * File: app/controller/BookingController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.BookingController', {
    extend: 'Ext.app.Controller',

    requires: [
        'layout.controller.override.BookingController'
    ],

    refs: [
        {
            ref: 'comgrp1bkgCreateBooking',
            selector: '#CreateBooking'
        }
    ],

    onHomeBtnViewBkgClick: function(button, e, eOpts) {
        var grid = Ext.getCmp('mygridpanel');
        if(grid.getSelectionModel().getSelection().length===1){
        var selected = grid.getSelectionModel().getSelection();
        var selectedBooking =[];
        Ext.iterate(selected,function(key){
        selectedBooking.push({BOOKING_NUM:key.data.BOOKING_NUM}) ;
        openBkgType = "view";

        var createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');

        Ext.getCmp('txtBkgNum').setValue(selectedBooking[0].BOOKING_NUM);

        //var home = Ext.create('layout.view.com.grp1.bkg.vpHome');

        createbkg.show();
        createbkg.setTitle("View");

        Ext.getCmp('com.grp1.bkg.vpHome').setDisabled(true);

        });
        }else{
            alert('Select only 1 record to view');
        }








    },

    onHomeBtnCreateBkgClick: function(button, e, eOpts) {
        openBkgType = "create";
        //alert(openBkgType);

        var createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');
        //createabkg2 = Ext.cmp(layout.view.com.grp1.bkg.CreateBooking);
        createbkg.show();
        this.vpHome = Ext.create('layout.view.com.grp1.bkg.vpHome');
        this.vpHome.mask("","");
    },

    onHomeBtnEditBkgClick: function(button, e, eOpts) {
        openBkgType = "edit";

        var createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');
        createbkg.show();
        createbkg.setTitle("Edit");
        var home = Ext.create('layout.view.com.grp1.bkg.vpHome');
        home.mask("","");

        //Ext.getBody().mask('test');
    },

    onTxtCntrNumBlur: function(component, e, eOpts) {
        var cntrNum = Ext.getCmp('txtCntrNum').getValue();

        var pattern =  /^[A-Za-z]{4}[0-9]{6}?$/;

        if(cntrNum.match(pattern)){
         Ext.Msg.alert("Validation", cntrNum);
        }
        else{
            Ext.Msg.alert("Validation Error", "Container Number should first have 4 letters and 6 digits");
        }
    },

    onBtnCreateBkgClick: function(button, e, eOpts) {
        var cntrNum = Ext.getCmp('txtCntrNum').getValue(),
            cntrType = Ext.getCmp('cntrTypeComboBox').getValue(),
            cgoNature = Ext.getCmp('cgoNatureRadioGrp').getValue(),
            cgoDesc = Ext.getCmp('txtCgoDesc').getValue(),
            grossWeight = Ext.getCmp('txtGrossWeight').getValue(),
            grossUnit = Ext.getCmp('gUnitComboBox').getValue(),
            netWeight = Ext.getCmp('txtNetWeight').getValue(),
            netUnit = Ext.getCmp('nUnitComboBox').getValue(),
            fromCity = Ext.getCmp('fromCityComboBox').getValue(),
            toCity = Ext.getCmp('toCityComboBox').getValue(),
            shipper = Ext.getCmp('txtShipper').getValue(),
            consignee = Ext.getCmp('txtConsignee').getValue();

        if(cntrNum !== null && cntrType !== null && cgoDesc !== null && fromCity !== null && toCity !== null && shipper !== null && consignee !== null){
         alert("Hello!");
        }

        else{
           // Show error
         Ext.Msg.alert("Can't Create Booking", "Please complete all fields");
        }


    },

    onCreateBookingBeforeShow: function(component, eOpts) {
        if(openBkgType === 'view'){
             Ext.getCmp('txtCntrNum').disable();
             Ext.getCmp('cntrTypeComboBox').disable();
             Ext.getCmp('cgoNatureRadioGrp').disable();
             Ext.getCmp('txtCgoDesc').disable();
             Ext.getCmp('txtGrossWeight').disable();
             Ext.getCmp('gUnitComboBox').disable();
             Ext.getCmp('txtNetWeight').disable();
             Ext.getCmp('nUnitComboBox').disable();
             Ext.getCmp('fromCityComboBox').disable();
             Ext.getCmp('toCityComboBox').disable();
             Ext.getCmp('txtShipper').disable();
             Ext.getCmp('txtConsignee').disable();
             Ext.getCmp('btnCreateBkg').hide();


        }
        else if(openBkgType === 'edit'){
        //     var cntrNum = Ext.getCmp('txtCntrNum').getValue(),
        //     cntrType = Ext.getCmp('cntrTypeComboBox').getValue(),
        //     cgoNature = Ext.getCmp('cgoNatureRadioGrp').getValue(),
        //     cgoDesc = Ext.getCmp('txtCgoDesc').getValue(),
        //     grossWeight = Ext.getCmp('txtGrossWeight').getValue(),
        //     grossUnit = Ext.getCmp('gUnitComboBox').getValue(),
        //     netWeight = Ext.getCmp('txtNetWeight').getValue(),
        //     netUnit = Ext.getCmp('nUnitComboBox').getValue(),
        //     fromCity = Ext.getCmp('fromCityComboBox').getValue(),
        //     toCity = Ext.getCmp('toCityComboBox').getValue(),
        //     shipper = Ext.getCmp('txtShipper').getValue(),
        //     consignee = Ext.getCmp('txtConsignee').getValue();


             Ext.getCmp('txtCntrNum').setValue("OOLU123456");
             Ext.getCmp('cgoNatureRadioGrp').setValue("");
             Ext.getCmp('txtCgoDesc').setValue("Toys");
             Ext.getCmp('txtGrossWeight').setValue("20");
             Ext.getCmp('txtNetWeight').setValue("20");
             Ext.getCmp('txtShipper').setValue("OOCL");
             Ext.getCmp('txtConsignee').setValue("COSCO");
             Ext.getCmp('btnCreateBkg').setText('Update');


        }
    },

    onCreateBookingClose: function(panel, eOpts) {

        Ext.getCmp('com.grp1.bkg.vpHome').setDisabled(false);
    },

    init: function(application) {
        this.control({
            "#homeBtnViewBkg": {
                click: this.onHomeBtnViewBkgClick
            },
            "#homeBtnCreateBkg": {
                click: this.onHomeBtnCreateBkgClick
            },
            "#homeBtnEditBkg": {
                click: this.onHomeBtnEditBkgClick
            },
            "#txtCntrNum": {
                blur: this.onTxtCntrNumBlur
            },
            "#btnCreateBkg": {
                click: this.onBtnCreateBkgClick
            },
            "#CreateBooking": {
                beforeshow: this.onCreateBookingBeforeShow,
                close: this.onCreateBookingClose
            }
        });
    }

});
