/*
 * File: app/controller/CreateCustomerController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.CreateCustomerController', {
    extend: 'Ext.app.Controller',

    id: 'CreateCustomerController',

    refs: [
        {
            ref: 'comgrp1bkgCreateCustomer',
            selector: '#CreateCustomer'
        },
        {
            ref: 'customerbtnCreate',
            selector: '#customerbtnCreate'
        }
    ],

    onTabCustomerBtnCreateClick: function(button, e, eOpts) {
        var createCustomerWindow = Ext.create('layout.view.com.grp1.bkg.CreateCustomer');
        createCustomerWindow.show();
    },

    onCustomerbtnCreateClick: function(button, e, eOpts) {
        var modelId = 'layout.model.';
        var checkActive;
        if(Ext.getCmp('customertxtfCustomer').getValue()===true){
            checkActive = 1;
        }else{
            checkActive = 0;
        }

        		var user = Ext.create(modelId + 'CustomerCreationModel', {
                    firstname : Ext.getCmp('customertxtfFirstName').getValue(),
                    lastname : Ext.getCmp('customertxtfLastName').getValue(),
                     address : Ext.getCmp('customertxtfAddress').getValue(),
                     companyName : Ext.getCmp('customertxtfCompanyName').getValue(),
                    contactNumber : Ext.getCmp('customertxtfContactNumber').getValue(),
                     mailAddress : Ext.getCmp('customertxtfEmail').getValue(),
                    role : Ext.getCmp('customertxtfRole').getValue(),
                    isActive : checkActive,
                    username : Ext.getCmp('customertxtfUsername').getValue(),
                    password : Ext.getCmp('customertxtfPassword').getValue()
        		});


        Ext.Ajax.request({
        			url : 'createCustomer',
        			method : 'POST',
        			jsonData : Ext.encode(user.data),
        			success : function(response) {
        				var res = Ext.decode(response.responseText);

        			},
        			failure : function(response) {
                        alert('Failed to save');
        			}
        		});
    },

    init: function(application) {
        this.control({
            "#tabCustomerBtnCreate": {
                click: this.onTabCustomerBtnCreateClick
            },
            "#customerbtnCreate": {
                click: this.onCustomerbtnCreateClick
            }
        });
    }

});
