/*
 * File: app/controller/LoginControllers.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.LoginControllers', {
    extend: 'Ext.app.Controller',

    onBtnLoginClick: function(button, e, eOpts) {
        		var modelId = 'layout.model.';

        		var user = Ext.create(modelId + 'LoginModel', {
                    username : Ext.getCmp('txfUsername').getValue(),
                    password : Ext.getCmp('txfPassword').getValue()
        		});

        		Ext.Ajax.request({
        			url : 'login',
        			method : 'POST',
        			jsonData : Ext.encode(user.data),
        			success : function(response) {
        				var res = Ext.decode(response.responseText);
        				console.log(response);
        				if(res.isSucces === "true"){
                            var store = Ext.getStore('LoginResponseStore');
                            store.removeAll();
                            store.add({username:res.username,accountId:res.accountId,custId: res.custId,role: res.role,isSuccess:res.isSucces});
        					this.vpHome = Ext.create('layout.view.com.grp1.bkg.vpHome');
        					this.vpHome.show();
        				}
        			},
        			failure : function(response) {
                        var jsonn = '{isSuccess: "true",role: "userkoto",userId: 123,accountid: "CUSTOMER"}';
        				var res = Ext.decode(jsonn);
        				//console.log(res);
                        ///////TO REMOVE//////
                        var store = Ext.getStore('LoginResponseStore');
                        store.removeAll();
                            store.add({username:'FAILED',accountId:123,custId: 333,role: 'ADMIN',isSuccess:'true'});
                        console.log(store);
                        //////////////////////
                            this.vpHome = Ext.create('layout.view.com.grp1.bkg.vpHome');
        					this.vpHome.show();
        				console.log("Update function ajax request failed");
        			}
        		});
    },

    init: function(application) {
        this.control({
            "#btnLogin": {
                click: this.onBtnLoginClick
            }
        });
    }

});
