/*
 * File: app/controller/AdminController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.AdminController', {
    extend: 'Ext.app.Controller',

    onTabAdminBtnSearchClick: function(button, e, eOpts) {
        var resultGrid = Ext.getCmp('tabAdminGridAcctList');
        var username = Ext.getCmp('tabAdminTxtfSearch').getValue();
        Ext.Ajax.request({
            url : 'searchAccounts',
            method : 'POST',
            jsonData : Ext.encode(username),
            success : function(response){
            	if(response.responseText !== '[null]'){
            		var res = Ext.decode(response.responseText);
            		console.log(response.responseText);
            		resultGrid.getStore().loadData(res);
                }
                else{
                	alert('Not Found');
                	resultGrid.getStore().removeAll();
                	resultGrid.getStore().sync();
                	resultGrid.getStore().refresh();
                }
                	
            },
            failure : function(response){
                alert('Search Failed');
            }
        });
    },
    
    onTabAdminBtnRefreshClick: function(button, e, eOpts) {
    	var resultGrid = Ext.getCmp('tabAdminGridAcctList');
    	Ext.getCmp('tabAdminTxtfSearch').setValue('');
    	resultGrid.getStore().removeAll();
    	resultGrid.getStore().sync();
    	resultGrid.getStore().refresh();
    },
    
    onTabAdminRbCreateChange: function(field, newValue, oldValue, eOpts) {
    	var create = Ext.getCmp('tabAdminRbCreate').getValue();

        if(create)
        {
            Ext.getCmp('tabAdminGridAcctList').disable();
            Ext.getCmp('tabAdminTxtfSearch').disable();
            Ext.getCmp('tabAdminBtnRefresh').disable();
            Ext.getCmp('tabAdminBtnSearch').disable();

            var resultGrid = Ext.getCmp('tabAdminGridAcctList');
        	Ext.getCmp('tabAdminTxtfSearch').setValue('');
        	resultGrid.getStore().removeAll();
        	resultGrid.getStore().sync();
        	resultGrid.getStore().refresh();
        }
        else{
        	Ext.getCmp('tabAdminGridAcctList').enable();
            Ext.getCmp('tabAdminTxtfSearch').enable();
            Ext.getCmp('tabAdminBtnRefresh').enable();
            Ext.getCmp('tabAdminBtnSearch').enable();
        }
    },
    
    init: function(application) {
        this.control({
            "#tabAdminBtnSearch": {
                click: this.onTabAdminBtnSearchClick
            },
            "#tabAdminBtnRefresh": {
                click: this.onTabAdminBtnRefreshClick
            },
            "#tabAdminRbCreate": {
                change: this.onTabAdminRbCreateChange
            }
        });
    }

});
