/*
 * File: app/controller/AdminController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.AdminController', {
    extend: 'Ext.app.Controller',

    onTabAdminBtnSearchClick: function(button, e, eOpts) {
        var resultGrid = Ext.getCmp('tabAdminGridAcctList');
        var username = Ext.getCmp('tabAdminTxtfSearch').getValue();
        Ext.Ajax.request({
            url : 'searchAccounts',
            method : 'POST',
            jsonData : Ext.encode(username),
            success : function(response){
            	if(response.responseText !== '[null]'){
            		var res = Ext.decode(response.responseText);
            		console.log(response.responseText);
            		resultGrid.getStore().loadData(res);
                }
                else{
                	alert('Not Found');
                	resultGrid.getStore().removeAll();
                	resultGrid.getStore().sync();
                }
                	
            },
            failure : function(response){
                alert('Search Failed');
            }
        });
    },
    
    onTabAdminBtnRefreshClick: function(button, e, eOpts) {
    	var resultGrid = Ext.getCmp('tabAdminGridAcctList');
    	Ext.getCmp('tabAdminTxtfSearch').setValue('');
    	resultGrid.getStore().removeAll();
    	resultGrid.getStore().sync();

		Ext.getCmp('tabAdminTxtfUsername').setValue('');
		Ext.getCmp('tabAdminTxtfPassword').setValue('');
		Ext.getCmp('tabAdminCbRole').setValue('');
    },
    
    onTabAdminRbCreateChange: function(field, newValue, oldValue, eOpts) {
    	var create = Ext.getCmp('tabAdminRbCreate').getValue();
    	
        if(create)
        {
        	Ext.getCmp('tabAdminRbUpdate').setValue(false);
        	Ext.getCmp('tabAdminRbCreate').setValue(true);
            Ext.getCmp('tabAdminGridAcctList').disable();
            Ext.getCmp('tabAdminTxtfSearch').disable();
            Ext.getCmp('tabAdminBtnRefresh').disable();
            Ext.getCmp('tabAdminBtnSearch').disable();

            var resultGrid = Ext.getCmp('tabAdminGridAcctList');
        	Ext.getCmp('tabAdminTxtfSearch').setValue('');
        	resultGrid.getStore().removeAll();
        	resultGrid.getStore().sync();
        	Ext.getCmp('tabAdminTxtfUsername').setValue('');
    		Ext.getCmp('tabAdminTxtfPassword').setValue('');
    		Ext.getCmp('tabAdminCbRole').setValue('');
        }
        else{
        	Ext.getCmp('tabAdminRbUpdate').setValue(true);
        	Ext.getCmp('tabAdminRbCreate').setValue(false);
        	Ext.getCmp('tabAdminGridAcctList').enable();
            Ext.getCmp('tabAdminTxtfSearch').enable();
            Ext.getCmp('tabAdminBtnRefresh').enable();
            Ext.getCmp('tabAdminBtnSearch').enable();
            Ext.getCmp('tabAdminTxtfUsername').setValue('');
    		Ext.getCmp('tabAdminTxtfPassword').setValue('');
    		Ext.getCmp('tabAdminCbRole').setValue('');
        }
    },
    
    onTabAdminGridAcctListSelect: function(rowmodel, record, index, eOpts) {
    	var acctGrid = Ext.getCmp('tabAdminGridAcctList');
    	if (acctGrid.getSelectionModel().hasSelection()) {
    		   var row = acctGrid.getSelectionModel().getSelection()[0];
    		   var username = row.data.username;
    		   var password = row.data.password;
    		   var role = row.data.role;
    		   Ext.getCmp('tabAdminTxtfUsername').setValue(username);
    		   Ext.getCmp('tabAdminTxtfPassword').setValue(password);
    		   Ext.getCmp('tabAdminCbRole').setValue(role);
    		}
    },
    
    onTabAdminBtnResetClick: function(button, e, eOpts) {
		   Ext.getCmp('tabAdminTxtfUsername').setValue('');
		   Ext.getCmp('tabAdminTxtfPassword').setValue('');
		   Ext.getCmp('tabAdminCbRole').setValue('');
    },
    
    onTabAdminBtnSaveClick: function(button, e, eOpts) {
    	var create = Ext.getCmp('tabAdminRbCreate').getValue();
    	var Username = Ext.getCmp('tabAdminTxtfUsername').getValue();
    	var Password = Ext.getCmp('tabAdminTxtfPassword').getValue();
    	var Role = Ext.getCmp('tabAdminCbRole').getValue();
    	var acctGrid = Ext.getCmp('tabAdminGridAcctList');
    	if (acctGrid.getSelectionModel().hasSelection()) {
 		   var row = acctGrid.getSelectionModel().getSelection()[0];
    	}
    	
    	var acct;
    	
    	if (create) { //create acct
    		acct= Ext.create('layout.model.AccountModel', {
	    		username : Username,
	            password : Password,
	            acctID : 123,
	            custID : 123 ,
	            role : Role
			});
    		Ext.Ajax.request({
    			url : 'createAccount',
    	        method : 'POST',
    	        jsonData : Ext.encode(acct.data),
    	        success : function(response){
    	        	console.log(response.responseText);
    	        	if(response.responseText === 'true'){
    	        		alert('Account Successfully Created');
    	        		Ext.getCmp('tabAdminTxtfUsername').setValue('');
    	        		Ext.getCmp('tabAdminTxtfPassword').setValue('');
    	        		Ext.getCmp('tabAdminCbRole').setValue('');
    	        	}
    	        	else {
    	        		alert('Account Failed to Create');
    	        	}
    	        },
    	        failure : function(response){
    	        	alert('Account Failed to Create');
    	        }
    		 });
    	}
    	else { //edit acct
    		acct = Ext.create('layout.model.AccountModel', {
        		username : Username,
                password : Password,
                acctID : row.data.acctID,
                custID : 123,
                role : Role
    		});
    		Ext.Ajax.request({
	            url : 'updateAccount',
	            method : 'POST',
	            jsonData : Ext.encode(acct.data),
	            success : function(response){
	            	console.log(response.responseText);
	            	if(response.responseText === 'true'){
	            		alert('Account Successfully Updated');
	         		   	Ext.getCmp('tabAdminTxtfUsername').setValue('');
	         		   	Ext.getCmp('tabAdminTxtfPassword').setValue('');
	         		   	Ext.getCmp('tabAdminCbRole').setValue('');
	            	}
	            	else {
	            		alert('Account Failed to Update');
	            	}
	            },
	            failure : function(response){
	            	alert('Account Failed to Update');
	            }
		 });
    	}
    	
    	
    },

    onTabAdminBtnDeleteClick: function(button, e, eOpts) {
    	var create = Ext.getCmp('tabAdminRbCreate').getValue();
    	var Username = Ext.getCmp('tabAdminTxtfUsername').getValue();
    	var Password = Ext.getCmp('tabAdminTxtfPassword').getValue();
    	var Role = Ext.getCmp('tabAdminCbRole').getValue();
    	var acctGrid = Ext.getCmp('tabAdminGridAcctList');
    	if (acctGrid.getSelectionModel().hasSelection()) {
 		   var row = acctGrid.getSelectionModel().getSelection()[0];
    	}
    	
    	var acct = Ext.create('layout.model.AccountModel', {
    		username : Username,
            password : Password,
            acctID : row.data.acctID,
            custID : row.data.custID,
            role : Role
		});
		Ext.Ajax.request({
            url : 'deleteAccount',
            method : 'POST',
            jsonData : Ext.encode(acct.data),
            success : function(response){
            	console.log(response.responseText);
            	if(response.responseText === 'true'){
            		alert('Account Successfully Deleted');
         		   	Ext.getCmp('tabAdminTxtfUsername').setValue('');
         		   	Ext.getCmp('tabAdminTxtfPassword').setValue('');
         		   	Ext.getCmp('tabAdminCbRole').setValue('');
         		    acctGrid.getStore().removeAll();
         		    acctGrid.getStore().sync();
            	}
            	else {
            		alert('Account Failed to Delete');
            	}
            },
            failure : function(response){
            	alert('Account Failed to Delete');
            }
	 });
    },
    
    init: function(application) {
        this.control({
            "#tabAdminBtnSearch": {
                click: this.onTabAdminBtnSearchClick
            },
            "#tabAdminBtnRefresh": {
                click: this.onTabAdminBtnRefreshClick
            },
            "#tabAdminRbCreate": {
                change: this.onTabAdminRbCreateChange
            },
            "#tabAdminGridAcctList": {
                select: this.onTabAdminGridAcctListSelect
            },
            "#tabAdminBtnReset": {
                click: this.onTabAdminBtnResetClick
            },
            "#tabAdminBtnSave": {
                click: this.onTabAdminBtnSaveClick
            },
            "#tabAdminBtnDelete": {
                click: this.onTabAdminBtnDeleteClick
            }
        });
    }

});
