/*
 * File: app/controller/BookingController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
var openBkgType;
var createbkg;
var home;
Ext.define('layout.controller.BookingController', {
    extend: 'Ext.app.Controller',
    refs: [
        {
            ref: 'comgrp1bkgCreateBooking',
            selector: '#CreateBooking'
        },
        {
            ref: 'comgrp1bkgvpHome',
            selector: '#com.grp1.bkg.vpHome'
        }
    ],

    onHomeBtnViewBkgClick: function(button, e, eOpts) {
        openBkgType = "view";
        createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');
        createbkg.show();
        createbkg.setTitle("View");
    },

    onHomeBtnCreateBkgClick: function(button, e, eOpts) {
        openBkgType = "create";
        createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');
        createbkg.show();
    },

    onHomeBtnEditBkgClick: function(button, e, eOpts) {
        openBkgType = "edit";
        createbkg = Ext.create('layout.view.com.grp1.bkg.CreateBooking');
        createbkg.show();
        createbkg.setTitle("Edit");
    },

    onTxtCntrNumBlur: function(component, e, eOpts) {
        var cntrNum = Ext.getCmp('txtCntrNum').getValue();

        var pattern =  /^[A-Za-z]{4}[0-9]{6}?$/;

        if(cntrNum.match(pattern)){
        }
        else{
            Ext.Msg.alert("Validation Error", "Container Number should first have 4 letters and 6 digits");
        }
    },

    onBtnCreateBkgClick: function(button, e, eOpts) {
        var cntrNum = Ext.getCmp('txtCntrNum').getValue(),
            cntrType = Ext.getCmp('cntrTypeComboBox').getValue(),
            cgoNature,
            cgoDesc = Ext.getCmp('txtCgoDesc').getValue(),
            GrossWeight = Ext.getCmp('txtGrossWeight').getValue(),
            GrossUnit = Ext.getCmp('gUnitComboBox').getValue(),
            NetWeight = Ext.getCmp('txtNetWeight').getValue(),
            NetUnit = Ext.getCmp('nUnitComboBox').getValue(),
            FromCity = Ext.getCmp('fromCityComboBox').getValue(),
            ToCity = Ext.getCmp('toCityComboBox').getValue(),
            shipper = Ext.getCmp('txtShipper').getValue(),
            consignee = Ext.getCmp('txtConsignee').getValue(),
            isWtValid,
        	isGoodCust,
        	isDocApproved,
        	isGC = Ext.getCmp('GCRadioButton').getValue(),
        	isDG = Ext.getCmp('DGRadioButton').getValue(),
        	isAW = Ext.getCmp('AWRadioButton').getValue(),
        	isRF = Ext.getCmp('RFRadioButton').getValue(),
        	isConfirmed;
        if(isGC){
        	cgoNature = 'GC';
        }
        if(isRF){
        	cgoNature = 'RF';
        }
        if(isAW){
        	cgoNature = 'AW';
        }
        if(isDG){
        	cgoNature = 'DG';
        }
        /*
            isWtValid = Ext.getCmp('chkWtValid').getValue(),
        	isGoodCust = Ext.getCmp('chkGoodCust').getValue(),
        	isDocApproved = Ext.getCmp('chkDocsApproved').getValue(),
        	*/
        if(Ext.getCmp('chkWtValid').getValue() === true)
        { isWtValid = 1; } else { isWtValid = 0; }
        if(Ext.getCmp('chkGoodCust').getValue() === true)
        { isGoodCust = 1; } else { isGoodCust = 0; }
        if(Ext.getCmp('chkDocsApproved').getValue() === true)
        { isDocApproved = 1; } else { isDocApproved = 0; }
        
        //create or edit
        if(cntrNum !== null && cntrType !== null && cgoDesc !== null && FromCity !== null && ToCity !== null && shipper !== null && consignee !== null){
        	if(isWtValid && isGoodCust && isDocApproved){
        		var bkg = Ext.create('layout.model.BookingInfoModel', {
        			bookingNum : 201700027,
        			shipperId : 1001,
        			consigneeId : 1003,
        			containerNumber : cntrNum,
        			containerType : cntrType,
        			cargoNature : cgoNature,
        			cargoDescrpiption : cgoDesc,
        			grossWeight : GrossWeight,
        			netWeight : NetWeight,
        			fromCity : FromCity,
        			toCity : ToCity,
        			createdBy : Ext.getCmp('txtfUsername').getValue(),
        			createDate : "12/12/2017",
        			updatedBy : Ext.getCmp('txtfUsername').getValue(),
        			updateDate : "12/12/2017",
        			isActive : 0,
        			grossUnit : GrossUnit,
        			netUnit : NetUnit,
        			isWeightValid : isWtValid,
        			isCustomerGood : isGoodCust,
        			isDocumentApproved : isDocApproved,
        			isConfirmed : 1
        		});
        	}else{
        		var bkg = Ext.create('layout.model.BookingInfoModel', {
        			bookingNum : 201700027,
        			shipperId : 1001,
        			consigneeId : 1003,
        			containerNumber : cntrNum,
        			containerType : cntrType,
        			cargoNature : cgoNature,
        			cargoDescrpiption : cgoDesc,
        			grossWeight : GrossWeight,
        			netWeight : NetWeight,
        			fromCity : FromCity,
        			toCity : ToCity,
        			createdBy : Ext.getCmp('txtfUsername').getValue(),
        			createDate : "20170101",
        			updatedBy : Ext.getCmp('txtfUsername').getValue(),
        			updateDate : "20170101",
        			isActive : 0,
        			grossUnit : GrossUnit,
        			netUnit : NetUnit,
        			isWeightValid : isWtValid,
        			isCustomerGood : isGoodCust,
        			isDocumentApproved : isDocApproved,
        			isConfirmed : 0
        		});
        	}
        	if(openBkgType === "create"){
        			Ext.Ajax.request({
        				url : 'createBkg',
        				method : 'POST',
        				jsonData : Ext.encode(bkg.data),
        				success : function(response){
        					alert(response.responseText);
        					this.createbkg.close();
        				},
        				failure : function(response) {
        					alert("Create Booking Failed");
        					console.log(response);
        					console.log("Update function ajax request failed");
        				}
        			});
            }else if(openBkgType === "edit"){
        			Ext.Ajax.request({
        				url : 'editBkg',
        				method : 'POST',
        				jsonData : Ext.encode(bkg.data),
        				success : function(response){
        					alert(response.responseText);
        					this.createbkg.close();
        				},
        				failure : function(response) {
        					alert("Update Booking Failed");
        					console.log(response);
        					console.log("Update function ajax request failed");
        				}
        			});
        		}
        	else{
                Ext.Msg.alert("Can't Create Booking", "Validation Should be all true");
        	}
        }
        else{
           // Show error
         Ext.Msg.alert("Can't Create Booking", "Please complete all fields");
        }
    },

    onCreateBookingBeforeShow: function(component, eOpts) {
    	var txtCntrNum = Ext.getCmp('txtCntrNum');
    	var cntrTypeComboBox = Ext.getCmp('cntrTypeComboBox');
    	var cgoNatureRadioGrp = Ext.getCmp('cgoNatureRadioGrp');
    	var txtCgoDesc = Ext.getCmp('txtCgoDesc');
    	var txtGrossWeight = Ext.getCmp('txtGrossWeight');
    	var gUnitComboBox = Ext.getCmp('gUnitComboBox');
    	var txtNetWeight = Ext.getCmp('txtNetWeight');
    	var nUnitComboBox = Ext.getCmp('nUnitComboBox');
    	var fromCityComboBox = Ext.getCmp('fromCityComboBox');
    	var toCityComboBox = Ext.getCmp('toCityComboBox');
    	var txtShipper = Ext.getCmp('txtShipper');
    	var txtConsignee = Ext.getCmp('txtConsignee');
    	var btnCreateBkg = Ext.getCmp('btnCreateBkg');
    	var chkWtValid = Ext.getCmp('chkWtValid');
    	var chkGoodCust = Ext.getCmp('chkGoodCust');
    	var chkDocsApproved = Ext.getCmp('chkDocsApproved');
    	
    	var store = Ext.getStore('ShipperConsigneeStore');
    	var companies = [];
    	Ext.Ajax.request({
    	    url : 'getParty',
    	    method : 'GET',
    	    success : function(response){
    	    	var res = Ext.decode(response.responseText);
    	    	Ext.each(res, function(obj){
    	    		var company = Ext.create('layout.model.ShipperConsigneeModel', {
    					id : obj.id,
    					companyName :  obj.companyName
    				});
//    	    		console.log(company);
    	    		companies.push(company.data);
    	    		
    	    		
    	    		
    	    	});
    	    	store.add(companies);
    	    	console.log(store);
    	    	console.log(store.getCount());
    	    },
    	    failure : function(response){}
    	});
    	
    	
        if(openBkgType === 'view'){
        	txtCntrNum.disable();
        	cntrTypeComboBox.disable();
        	cgoNatureRadioGrp.disable();
        	txtCgoDesc.disable();
        	txtGrossWeight.disable();
        	gUnitComboBox.disable();
        	txtNetWeight.disable();
        	nUnitComboBox.disable();
        	fromCityComboBox.disable();
        	toCityComboBox.disable();
        	txtShipper.disable();
        	txtConsignee.disable();
        	btnCreateBkg.hide();
        	chkWtValid.disable();
        	chkGoodCust.disable();
        	chkDocsApproved.disable();
        }
        else if(openBkgType === 'edit'){
        	txtCntrNum.setValue("OOLU123456");
        	cgoNatureRadioGrp.setValue("");
        	txtCgoDesc.setValue("Toys");
        	txtGrossWeight.setValue("20");
        	txtNetWeight.setValue("20");
        	txtShipper.setValue("OOCL");
        	txtConsignee.setValue("COSCO");
        	btnCreateBkg.setText('Update');
        }
    },

    onCreateBookingClose: function(panel, eOpts) {
        createbkg.destroy();
    },

    init: function(application) {
        this.control({
            "#homeBtnViewBkg": {
                click: this.onHomeBtnViewBkgClick
            },
            "#homeBtnCreateBkg": {
                click: this.onHomeBtnCreateBkgClick
            },
            "#homeBtnEditBkg": {
                click: this.onHomeBtnEditBkgClick
            },
            "#txtCntrNum": {
                blur: this.onTxtCntrNumBlur
            },
            "#btnCreateBkg": {
                click: this.onBtnCreateBkgClick
            },
            "#CreateBooking": {
                beforeshow: this.onCreateBookingBeforeShow,
                close: this.onCreateBookingClose
            }
        });
    }

});
