/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExampleHW.controller.MyController', {
    extend: 'Ext.app.Controller',

    onButtonClick: function(button, e, eOpts) {
        var txtVal = Ext.getCmp("txtValue");
        var txt = txtVal.getValue();

        Ext.define('testClass',{
            testId:'123',
            testValue:''
        });

        var test = Ext.create('testClass');
        test.testId = 123;
        test.testValue = txt;


        Ext.Ajax.request({
            url: 'create',
            success: function(response){
                var result = Ext.decode(response.responseText);
                alert('Success');
            },
            failure: function(){
                alert('Fail');
            },
            params : { test : Ext.encode(test)}
        });


    },

    init: function(application) {
        this.control({
            "#btnInsert": {
                click: this.onButtonClick
            }
        });
    }

});
