/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({
	appFolder:'../group1Booking/js/booking/app',
	models: [
        'searchBookingByAny',
        'LocationModel',
        'CustomerModel',
        'BookingInfoModel',
        'AccountModel',
        'LoginModel',
        'LoginResponse',
        'LoginModel',
        'ShipperConsigneeModel',
        'CustomerCreationModel',
        'SearchCustomerModel'
    ],
    stores: [
        'CustomerStore',
        'AccountStore',
        'LocationStore',
        'LoginResponseStore',
        'BookingInfoStore',
        'ShipperConsigneeStore',
        'AccountListsStore'
    ],
    views: [
        'com.grp1.bkg.vpHome',
        'com.grp1.bkg.CreateBooking',
        'com.grp1.bkg.CreateCustomer',
		'com.grp1.bkg.vpLogin'
    ],
    controllers: [
        'LoginControllers',
        'HomeController',
        'BookingController',
        'CreateCustomerController',
        'AdminController'
    ],
    name: 'layout',

    launch: function() {
        this.vpLogin = Ext.create('layout.view.com.grp1.bkg.vpLogin');
    }

});
